CREATE TABLE Bans (
	BanID INTEGER NOT NULL,
	PlayerID INTEGER NOT NULL,
	AdminName VARCHAR(255) NOT NULL,
	BanDate DATETIME NOT NULL,
	BanExpiryDate DATETIME NOT NULL,
	CONSTRAINT Bans_PK PRIMARY KEY (BanID)
);