CREATE TABLE IPBans (
	IPAddress INTEGER NOT NULL,
	AdminName VARCHAR(255) NOT NULL,
	BannedDate DATETIME NOT NULL,
	BannedUntilDate DATETIME NOT NULL,
	CONSTRAINT IPBans_PK PRIMARY KEY (IPAddress)
);